### ISSUE TITLE
problem with 8idi:m25 and tqdm scroll bar

### ISSUE THREAD

**Issue by prjemian** [aps-8id-trr/ipython-8idiuser#126]
When using [`8idi:m25` (*fccdx*)](https://github.com/aps-8id-trr/ipython-8idiuser/issues/124#issuecomment-571781340) as a test motor to help diagnose #124, a [problem](https://github.com/bluesky/ophyd/pull/788#issuecomment-572742274) with the *tqdm* scroll bars was reported.  The problem did not stop the plan but *did* stop the scroll bar from working.

The problem can be seen with this example:

```python
In [1]: m25 = EpicsMotor("8idi:m25", name="m25")                                                                        

In [2]: m25.position                                                                                                    
Out[2]: -45.99867499999999

In [3]: m25.velocity                                                                                                    
Out[3]: EpicsSignal(read_pv='8idi:m25.VELO', name='m25_velocity', parent='m25', value=3.81, timestamp=1578601788.08614, tolerance=1e-06, auto_monitor=False, string=False, write_pv='8idi:m25.VELO', limits=False, put_complete=False)

In [4]: m25.velocity.value                                                                                              
Out[4]: 3.81

In [5]: RE(bps.mv(m25, -46.1))                                                                                          
[E 15:30:54.632 ophydobj:476] Subscription readback callback exception (EpicsMotor(prefix='8idi:m25', name='m25', settle_time=0.0, timeout=None, read_attrs=['user_readback', 'user_setpoint'], configuration_attrs=['user_offset', 'user_offset_dir', 'velocity', 'acceleration', 'motor_egu']))
    Traceback (most recent call last):
      File "/home/beams10/8IDIUSER/Documents/jemian/ophyd/ophyd/ophydobj.py", line 471, in inner
        cb(*args, **kwargs)
      File "/home/beams10/8IDIUSER/Documents/jemian/ophyd/ophyd/status.py", line 496, in _notify_watchers
        fraction=fraction)
      File "/home/beams/8IDIUSER/.conda/envs/bluesky/lib/python3.7/site-packages/bluesky/utils.py", line 1098, in update
        ncols=self.ncols)
      File "/home/beams/8IDIUSER/.conda/envs/bluesky/lib/python3.7/site-packages/tqdm/std.py", line 482, in format_meter
        charset=Bar.ASCII if ascii is True else ascii or Bar.UTF)
      File "/home/beams/8IDIUSER/.conda/envs/bluesky/lib/python3.7/site-packages/tqdm/std.py", line 146, in __init__
        assert 0 <= frac <= 1
    AssertionError
Out[5]: ()                                                                                                              
```

**Comment by prjemian** [comment]
As [noted](https://github.com/bluesky/ophyd/pull/788#issuecomment-572785778), 

> Ok, that problem is specific to the `8idi:m25` motor we used for testing.  It fails the `assert 0 <= frac <= 1` with `frac=1.0132136624283221` and that needs to be traced down in a beamline-specific issue.
> 
> I've tested at the beam line with a different test motor PV (`prj:m1`, a soft motor instance from a soft IOC in my office a few subnets away). No such errors reported.

```
(bluesky) 8idiuser@quartz ~ $ export EPICS_CA_ADDR_LIST=164.54.104.17
(bluesky) 8idiuser@quartz ~ $ caget prj:m1 prj:UPTIME
prj:m1                         -45
prj:UPTIME                     00:41:00
(bluesky) 8idiuser@quartz ~ $ bluesky8IDI 
```

**Comment by prjemian** [comment]
Also tested with an instance of `ophyd.sim.SynAxis()` (ophyd simulated non-EPICS motor) and no problem.  BUT, this is not a great test because the tqdm scroll bar is not drawn since the move is instantaneous (acceleration and velocity are at the speed of writing to program memory).  Testing with a motor that has non-zero response time, such as a soft motor PV, was needed.

**Comment by prjemian** [comment]
So, why `8idi:m25`?  Something about the absolute position (-46 +/- < 10 mm)?

**Comment by prjemian** [comment]
Thanks @tacaswell for [finding](https://github.com/bluesky/bluesky/issues/1278) [where](https://github.com/bluesky/bluesky/blob/master/bluesky/utils.py#L1118) to fix this in the bluesky code base.
