### ISSUE TITLE
convert SPEC config to ophyd

### ISSUE THREAD

**Issue by prjemian** [aps-8id-trr/ipython-8idiuser#7]
Attempt a conversion of the 8-ID-I SPEC `config` file to ophyd using the [`spec2ophyd`](https://github.com/BCDA-APS/apstools/blob/master/apstools/migration/spec2ophyd.py) tool.  The tool is *experimental* so it may not be successful for the entire configuration.  Worth a try.

**Comment by prjemian** [comment]
Where are they?  Cannot find in ~8idiuser/spec

**Comment by prjemian** [comment]
Aha!  Found it by examining the `~/bin` directory: `/home/beams/S8SPEC/spec/config`

**Comment by prjemian** [comment]
The autoconversion script has a lot to learn.  First problem:

```
(base) bash-4.2$ python ./spec2ophyd.py
['MOT000 ', ' EPICS_M2:6/1   2000  1  2000  200   50  125    0 0x003     flyz  flyz']
['MOT001 ', '    NONE:2/64   2000  1  2000  200   50  125    0 0x003  StrainN  StrainN']
['MOT002 ', ' EPICS_M2:2/16   2000  1  2000  200   50  125    0 0x003     ti3y  ti3y']
['MOT003 ', ' EPICS_M2:2/41   2000  1  2000  200   50  125    0 0x003     si6b  si6b']
['MOT004 ', ' EPICS_M2:2/42   2000  1  2000  200   50  125    0 0x003     si6t  si6t']
['MOT005 ', ' EPICS_M2:2/55   2000  1  2000  200   50  125    0 0x003     si5x  si5x']
['MOT006 ', ' EPICS_M2:2/56   2000  1  2000  200   50  125    0 0x003     si5z  si5z']
['MOT007 ', ' EPICS_M2:2/43   2000  1  2000  200   50  125    0 0x003     si6B  si6B']
['MOT008 ', ' EPICS_M2:2/44   2000  1  2000  200   50  125    0 0x003     si6T  si6T']
['MOT009 ', ' EPICS_M2:2/129   2000  1  2000  200   50  125    0 0x003      tth  tth']
['MOTPAR:misc_par_1 ', ' sm1']
Traceback (most recent call last):
  File "./spec2ophyd.py", line 229, in <module>
    main()
  File "./spec2ophyd.py", line 224, in main
    spec_cfg.read_config()
  File "./spec2ophyd.py", line 184, in read_config
    motor = SpecMotor(line)
  File "./spec2ophyd.py", line 58, in __init__
    self.index = int(lr[0].strip("MOT"))
ValueError: invalid literal for int() with base 10: 'PAR:misc_par_1 '
```

which comes from this part of the config file:

```
# Motor    cntrl steps sign slew base backl accel nada  flags   mne  name
MOT000 = EPICS_M2:6/1   2000  1  2000  200   50  125    0 0x003     flyz  flyz
MOT001 =    NONE:2/64   2000  1  2000  200   50  125    0 0x003  StrainN  StrainN
MOT002 = EPICS_M2:2/16   2000  1  2000  200   50  125    0 0x003     ti3y  ti3y
MOT003 = EPICS_M2:2/41   2000  1  2000  200   50  125    0 0x003     si6b  si6b
MOT004 = EPICS_M2:2/42   2000  1  2000  200   50  125    0 0x003     si6t  si6t
MOT005 = EPICS_M2:2/55   2000  1  2000  200   50  125    0 0x003     si5x  si5x
MOT006 = EPICS_M2:2/56   2000  1  2000  200   50  125    0 0x003     si5z  si5z
MOT007 = EPICS_M2:2/43   2000  1  2000  200   50  125    0 0x003     si6B  si6B
MOT008 = EPICS_M2:2/44   2000  1  2000  200   50  125    0 0x003     si6T  si6T
MOT009 = EPICS_M2:2/129   2000  1  2000  200   50  125    0 0x003      tth  tth
MOTPAR:misc_par_1 = sm1
```

**Comment by prjemian** [comment]
Config file attached here for improving the converter.  Suggest reporting the unrecognized MOTPAR terms as comments marked TODO:

[config.txt](https://github.com/aps-8id-trr/ipython-8idiuser/files/3412869/config.txt)

**Comment by prjemian** [comment]
`spec2ophyd` tool ready to use from [master branch](https://github.com/BCDA-APS/apstools/blob/master/apstools/migration/spec2ophyd.py)
